# Generated by Django 5.0.4 on 2024-06-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_congregation_member_number_and_more'),
        ('structural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstructural',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='nonstructural',
            name='masteruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NonStructural', to='master.master', verbose_name='Data Master '),
        ),
        migrations.AlterField(
            model_name='nonstructural',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='priodestructural',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='priodestructural',
            name='end_date',
            field=models.DateField(verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='priodestructural',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Priode'),
        ),
        migrations.AlterField(
            model_name='priodestructural',
            name='start_date',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='priodestructural',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='structural',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='structural',
            name='masteruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Structural', to='master.master', verbose_name='Data Master'),
        ),
        migrations.AlterField(
            model_name='structural',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Structural'),
        ),
        migrations.AlterField(
            model_name='structural',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
