# Generated by Django 5.0.4 on 2024-06-28 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0002_alter_nonstructural_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNonStructrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nama Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah')),
            ],
            options={
                'verbose_name': 'Role Non Structural',
                'verbose_name_plural': 'Role Non Structural',
            },
        ),
        migrations.AlterField(
            model_name='nonstructural',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_non_structrual', to='structural.rolenonstructrual', verbose_name='Role'),
        ),
    ]
