# Generated by Django 5.0.4 on 2024-06-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0003_rolenonstructrual_alter_nonstructural_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleNonStructrual',
            new_name='RoleNonStructural',
        ),
    ]
