# Generated by Django 5.0.4 on 2024-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0004_rename_rolenonstructrual_rolenonstructural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstructural',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Role'),
        ),
        migrations.RemoveField(
            model_name='nonstructural',
            name='masteruser',
        ),
        migrations.DeleteModel(
            name='RoleNonStructural',
        ),
    ]
