# Generated by Django 5.0.4 on 2024-07-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_alter_baptism_options'),
        ('structural', '0005_alter_nonstructural_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonstructural',
            options={'verbose_name': 'Non Struktural', 'verbose_name_plural': 'Non Struktural'},
        ),
        migrations.AlterModelOptions(
            name='priodestructural',
            options={'verbose_name': 'Periode Struktural', 'verbose_name_plural': 'Periode Struktural'},
        ),
        migrations.AlterModelOptions(
            name='structural',
            options={'verbose_name': 'Struktural', 'verbose_name_plural': 'Struktural'},
        ),
        migrations.AlterField(
            model_name='structural',
            name='masteruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Struktural', to='master.master', verbose_name='Data Master'),
        ),
    ]
