# Generated by Django 5.0.4 on 2024-05-20 08:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementOfWorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Online'), (2, 'Offline'), (3, 'Hybrid')])),
                ('status', models.BooleanField(default=False)),
                ('qrcode', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Ibadah Gereja',
                'verbose_name_plural': 'Data Ibadah Gereja',
            },
        ),
        migrations.CreateModel(
            name='ManagementPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.PositiveIntegerField(blank=True, choices=[(1, 'Fingerprint'), (2, 'QR Code'), (3, 'RFID')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Absensi',
                'verbose_name_plural': 'Data Absensi',
            },
        ),
        migrations.CreateModel(
            name='ManagementPresenceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detail Data Absensi',
                'verbose_name_plural': 'Detail Data Absensi',
            },
        ),
    ]
