# Generated by Django 5.0.4 on 2024-05-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementofworship',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.location', verbose_name='Lokasi Gereja'),
        ),
        migrations.AddField(
            model_name='managementofworship',
            name='pendeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='managementpresence',
            name='masteruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresence', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='managementpresence',
            name='worship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresence', to='management.managementofworship', verbose_name='Ibadah Gereja'),
        ),
        migrations.CreateModel(
            name='ManagementPresenceCongregationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Detail Data Absensi Jemaat',
                'verbose_name_plural': 'Detail Data Absensi Jemaat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.managementpresence',),
        ),
        migrations.CreateModel(
            name='ManagementPresenceEmployeeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Detail Data Absensi Karyawan',
                'verbose_name_plural': 'Detail Data Absensi Karyawan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.managementpresence',),
        ),
        migrations.CreateModel(
            name='ManagementPresenceServantOfGodProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Detail Data Absensi Hamba Tuhan',
                'verbose_name_plural': 'Detail Data Absensi Hamba Tuhan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.managementpresence',),
        ),
        migrations.AddField(
            model_name='managementpresencedetail',
            name='presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresenceDetail', to='management.managementpresence', verbose_name='Data Absensi'),
        ),
    ]
