# Generated by Django 5.0.4 on 2024-05-28 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
        ('master', '0002_master_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masteruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RFIDCard', to='master.master', verbose_name='Master Data')),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Card',
            },
        ),
    ]
