# Generated by Django 5.0.4 on 2024-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rfidcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='id_rfid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
