# Generated by Django 5.0.4 on 2024-06-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rfidcard_id_rfid'),
        ('master', '0003_alter_family_options_alter_master_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementofworship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='pendeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.master', verbose_name='Data Master'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='managementpresence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='managementpresence',
            name='masteruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresence', to='master.master', verbose_name=' Data Master'),
        ),
        migrations.AlterField(
            model_name='managementpresence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='managementpresencedetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='managementpresencedetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='id_rfid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor RFID'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RFIDCard', to='master.master', verbose_name='Data Master'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
