# Generated by Django 5.0.4 on 2024-06-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_managementofworship_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidcard',
            name='id_rfid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nomor RFID'),
        ),
    ]
