# Generated by Django 5.0.4 on 2024-07-15 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_rfidcard_id_rfid'),
        ('master', '0014_alter_congregation_alias_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementofworship',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Waktu Akhir'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Waktu Mulai'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RFIDCard', to='master.congregation', verbose_name='Data Jemaat'),
        ),
    ]
