# Generated by Django 5.0.4 on 2024-07-16 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_managementofworship_end_time_and_more'),
        ('master', '0015_delete_baptismproxy_delete_congregationproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementpresence',
            name='length_of_work',
            field=models.TimeField(blank=True, null=True, verbose_name='Lama Kerja'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='wajib diisi', verbose_name='Waktu Selesai Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='location',
            field=models.ForeignKey(help_text='wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.location', verbose_name='Lokasi Pelaksanaan Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='name',
            field=models.CharField(help_text='wajib diisi', max_length=255, verbose_name='Nama Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='pendeta',
            field=models.ForeignKey(help_text='wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.master', verbose_name='Pembimbing Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='wajib diisi', verbose_name='Waktu Mulai Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='status',
            field=models.BooleanField(default=True, help_text='Checklis jika ingin menggunakan ibadah yang berbeda di waktu yang sama.'),
        ),
        migrations.AlterField(
            model_name='managementofworship',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Online'), (2, 'Offline'), (3, 'Hybrid')], help_text='wajib diisi', verbose_name='Jenis Ibadah'),
        ),
        migrations.AlterField(
            model_name='managementpresence',
            name='masteruser',
            field=models.ForeignKey(help_text='wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresence', to='master.master', verbose_name=' Data Master'),
        ),
        migrations.AlterField(
            model_name='managementpresencedetail',
            name='presence',
            field=models.ForeignKey(help_text='wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='ManagementPresenceDetail', to='management.managementpresence', verbose_name='Data Absensi'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='masteruser',
            field=models.OneToOneField(help_text='wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='RFIDCard', to='master.congregation', verbose_name='Data Jemaat'),
        ),
    ]
