# Generated by Django 5.0.4 on 2024-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_managementpresence_length_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementpresence',
            name='tag',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tag'),
        ),
    ]
