# Generated by Django 5.0.4 on 2024-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_managementpresence_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementofworship',
            name='day_worship',
            field=models.PositiveIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], default=0, verbose_name='Hari'),
        ),
    ]
