# Generated by Django 5.0.4 on 2024-07-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_managementofworship_day_worship'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementpresence',
            name='present',
            field=models.BooleanField(default=True, verbose_name='Hadir'),
        ),
        migrations.AlterField(
            model_name='managementpresence',
            name='tag',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tag (Id Perangkat Presensi)'),
        ),
    ]
