# Generated by Django 5.0.4 on 2024-07-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_managementpresence_present_and_more'),
        ('master', '0020_alter_master_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementofworship',
            name='pendeta',
            field=models.ForeignKey(help_text='wajib diisi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementOfWorship', to='master.master', verbose_name='Pembimbing Ibadah'),
        ),
    ]
