"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.staticfiles.storage import staticfiles_storage
from import_export.formats.base_formats import XLSX
from datetime import timedelta  
from dotenv import load_dotenv
load_dotenv()

EXPORT_FORMATS = [XLSX]
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET', 'django-insecure-d3#&r-@k_c&j!&-i8rj(7x=184mcc5(yt3jgu%o(!!kb$c&+@t')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', True)
# NOTE = Perbaiki
ALLOWED_HOSTS = [i for i in os.getenv('ALLOWED_HOSTS', 'gkim.dev-sti-group.biz.id').split(",")]

# NOTE = Perbaiki
CSRF_TRUSTED_ORIGINS = [ i for i in os.getenv('CSRF_TRUSTED_ORIGINS', 'https://gkim.dev-sti-group.biz.id').split(",")]

# Application definition

INSTALLED_APPS = [
    'baton',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'master',
    "nested_admin",
    'rangefilter',
    'warta',
    'tinymce',
    'adminsortable2',
    'management',
    'structural',
    'mptt',
    'django_mptt_admin',
    'setting',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'rest_framework.authtoken',
    'corsheaders',
    'django_admin_lightweight_date_hierarchy',
    'admin_auto_filters',
    'baton.autodiscover',
    'django_extensions',
    'crispy_forms',
    'crispy_bootstrap4',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOWED_ORIGINS = [i for i in os.getenv('CORS_ALLOWED_ORIGINS', 'https://gkim.dev-sti-group.biz.id').split(",")]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

ROOT_URLCONF = 'core.urls'
# template root
TEMPLATE_DIR = os.path.join(CORE_DIR, "core/templates")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
if os.getenv('DB_ENGINE', 'sqlite3') == 'sqlite3':
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'gkim'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', '192.168.109.80'),
            'PORT': os.getenv('DB_PORT', '5432')
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'id'
LANGUAGES = [
    ('id', 'Bahasa Indonesia'),
]

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = os.path.join(CORE_DIR, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'core/static'),
)
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

logo = '<img src="{}" class="logo-dark" alt="Greja" style="width:70%; ">'.format(staticfiles_storage.url("admin/img/logo.png"))
LIST_PER_PAGE = 10

BATON = {
    'SITE_HEADER': logo,
    'SITE_TITLE': 'GKIM',
    'INDEX_TITLE': 'Selamat Datang DI APP GKIM',
    'SUPPORT_HREF': 'https://www.skyline.net.id/contact-us/',
    'COPYRIGHT': 'copyright © 2024 <a href="https://gkimkaimtong.org/">GKIM</a>', # noqa
    'POWERED_BY': '<a href="https://www.skyline.net.id/">PT Skyline Semesta</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_ALWAYS_OPEN': False,
    'CHANGELIST_FILTERS_FORM': True,
    'COLLAPSABLE_USER_AREA': False,
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Menu',
    'MESSAGES_TOASTS': False,
    'GRAVATAR_DEFAULT_IMG': 'retro',
    'GRAVATAR_ENABLED': False,
    'FORCE_THEME': 'light',
    'LOGIN_SPLASH': '/static/admin/img/background.jpeg',
    'MENU': (
        { 'type': 'title', 'label': 'main'},
        {   
            'type': 'free',
            'name': 'auth',
            'label': 'Home',
            'icon': 'fa fa-home',
            'url' : '/admin/',
        },
        {
            'type': 'title', 
            'label': 'Master',
            'apps': ('master', ),
            'children' : [
                 {
                    'type' : 'free',
                    'label' : "Data Group",
                    'url' : '/admin/auth/group/',
                    'icon' : 'fa fa-user-group',
                },
                 {
                    'type' : 'free',
                    'label' : "Data Master",
                    'url' : '/admin/master/master/',
                    'icon' : 'fa fa-database',
                },
                {
                    'type' : 'free',
                    'label' : "Data Jemaat",
                    'url' : '/admin/master/congregation/',
                    'icon' : 'fa fa-users',
                },
                {
                    'type' : 'free',
                    'label' : "Data Hamba Tuhan",
                    'url' : '/admin/master/servantofgod/',
                    'icon' : 'fa fa-cross',
                },
                {
                    'type' : 'free',
                    'label' : "Data Karyawan",
                    'url' : '/admin/master/employee/',
                    'icon' : 'fa fa-users-line',
                },
                {
                    'type' : 'free',
                    'label' : "Data Keluarga",
                    'url' : '/admin/master/family/',
                    'icon' : 'fa fa-people-group',
                },
                {
                    'type' : 'free',
                    'label' : "Data Baptis / Atestasi",
                    'url' : '/admin/master/baptism/',
                    'icon' : 'fa fa-book-bible',
                },
                {
                    'type' : 'free',
                    'label' : "Data Galeri",
                    'url' : '/admin/master/gallery/',
                    'icon' : 'fa fa-folder',
                },
                {
                    'type' : 'free',
                    'label' : "Data Lokasi",
                    'url' : '/admin/master/location/',
                    'icon' : 'fa fa-location-pin',
                },
            ]
        },
        {
            'type': 'title', 
            'label': 'Management',
            'apps': ('management', ),
            'children' : [
                {
                    'type' : 'free',
                    'label' : "Semua Presensi",
                    'url' : '/admin/management/managementpresence/',
                    'icon' : 'fa fa-address-book',
                },
                {
                    'type' : 'free',
                    'label' : "Presensi Jemaat",
                    'url' : '/admin/management/managementpresencecongregationproxy/',
                    'icon' : 'fa fa-address-book',
                },
                {
                    'type' : 'free',
                    'label' : "Presensi Hamba Tuhan",
                    'url' : '/admin/management/managementpresenceservantofgodproxy/',
                    'icon' : 'fa fa-address-book',
                },
                {
                    'type' : 'free',
                    'label' : "Presensi Karyawan",
                    'url' : '/admin/management/managementpresenceemployeeproxy/',
                    'icon' : 'fa fa-address-book',
                },
                {
                    'type' : 'free',
                    'label' : "Management Ibadah",
                    'url' : '/admin/management/managementofworship/',
                    'icon' : 'fa fa-hands-praying',
                },
                {
                    'type' : 'free',
                    'label' : "Registrasi RFID",
                    'url' : '/admin/management/rfidcard/',
                    'icon' : 'fa fa-id-card',
                },
            ],
        },
        {
            'type': 'title', 
            'label': 'Struktur Organisasi',
            'apps': ('structural', ),
            'children' : [
                {
                    'type' : 'free',
                    'label' : "Priode Struktural",
                    'url' : '/admin/structural/priodestructural/',
                    'icon' : 'fa fa-calendar',
                },
                {
                    'type' : 'free',
                    'label' : "Struktural",
                    'url' : '/admin/structural/structural/',
                    'icon' : 'fa fa-sitemap',
                }, 
                {
                    'type' : 'free',
                    'label' : "Non Struktural",
                    'url' : '/admin/structural/nonstructural/',
                    'icon' : 'fa fa-user-slash',
                }, 
            ]
        },
        {
            'type': 'title', 
            'label': 'Informasi',
            'apps': ('warta', ),
            'children' : [
                {
                    'type' : 'free',
                    'label' : "Warta",
                    'url' : '/admin/warta/warta/',
                    'icon' : 'fa fa-newspaper',
                },
                {
                    'type' : 'free',
                    'label' : "Pengumuman",
                    'url' : '/admin/warta/announcement/',
                    'icon' : 'fa fa-bullhorn',

                }, 
            ]
        },
        # {
        #     'type': 'title', 
        #     'label': 'Setting',
        #     'apps': ('setting', ),
        #     'children' : [
        #         {
        #             'type' : 'free',
        #             'label' : "Setting",
        #             'url' : '/admin/setting/setting/',
        #             'icon' : 'fa fa-gear',
        #         },
        #     ]
        # },
        
    )
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'master.permission.HasGroupPermission',
    ),
}


AUTHENTICATION_BACKENDS = (
    'master.authentications.EmailAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ACCESS_TOKEN_LIFETIME = os.getenv('ACCESS_TOKEN_LIFETIME', 2)
REFRESH_TOKEN_LIFETIME = os.getenv('REFRESH_TOKEN_LIFETIME', 7)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=ACCESS_TOKEN_LIFETIME),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=REFRESH_TOKEN_LIFETIME),     
}

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}

EMAIL_HOST = os.getenv('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
EMAIL_PORT = os.getenv('EMAIL_PORT', 2525   )
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '537fed5061da54')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'e64eda9edcdac8')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Support Pixelac Quik <support@aeria.my.id>')