# Generated by Django 5.0.4 on 2024-05-20 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baptism_date', models.DateField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'Baptis Child'), (2, 'Baptism Adult')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Baptis',
                'verbose_name_plural': 'Data Baptis',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('religion', models.PositiveIntegerField(choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katholik'), (4, 'Hindu'), (5, 'Budha'), (6, 'Konghucu')])),
                ('bpjs_employment', models.IntegerField()),
                ('bpjs_health', models.IntegerField()),
                ('account_number', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('employee_position', models.CharField(max_length=255)),
                ('is_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Karyawan',
                'verbose_name_plural': 'Data Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Grandfather'), (2, 'Grandmother'), (3, 'Father'), (4, 'Mother'), (5, 'Child'), (6, 'Step Child'), (7, 'Adopted Child'), (8, 'Step Mother'), (9, 'Step Father')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Data',
                'verbose_name_plural': 'Family Data',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokasi Gereja',
                'verbose_name_plural': 'Lokasi Gereja',
            },
        ),
        migrations.CreateModel(
            name='BaptismProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Baptis',
                'verbose_name_plural': 'Data Baptis',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.baptism',),
        ),
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.IntegerField()),
                ('alias_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('is_congregation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('worship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Congregation', to='management.managementofworship', verbose_name='Ibadah Gereja')),
            ],
            options={
                'verbose_name': 'Data Jemaat',
                'verbose_name_plural': 'Data Jemaat',
            },
        ),
        migrations.AddField(
            model_name='baptism',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Baptism', to='master.congregation', verbose_name='Congregation Data'),
        ),
        migrations.CreateModel(
            name='CongregationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Jemaat',
                'verbose_name_plural': 'Data Jemaat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.congregation',),
        ),
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Karyawan',
                'verbose_name_plural': 'Data Karyawan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.employee',),
        ),
        migrations.CreateModel(
            name='FamilyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Keluarga',
                'verbose_name_plural': 'Data Keluarga',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.family',),
        ),
        migrations.CreateModel(
            name='GalleryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Gallery',
                'verbose_name_plural': 'Data Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.gallery',),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Man'), (2, 'Woman')])),
                ('address', models.CharField(max_length=255)),
                ('personal_identity', models.IntegerField()),
                ('blood_type', models.PositiveIntegerField(choices=[(1, 'A+'), (2, 'B+'), (3, 'AB+'), (4, 'O+'), (5, 'A-'), (6, 'B-'), (7, 'AB-'), (8, 'O-')])),
                ('marital_status', models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Masters', to='master.location', verbose_name='Church Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Data',
                'verbose_name_plural': 'Master Data',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='masteruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gallery', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='family',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='master.master', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='family',
            name='masteruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Family', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='employee',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Congregation', to='master.master', verbose_name='Master Data'),
        ),
        migrations.AddField(
            model_name='baptism',
            name='masteruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Baptism', to='master.master', verbose_name='Master Data'),
        ),
        migrations.CreateModel(
            name='ServantOfGod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.IntegerField()),
                ('ordination', models.DateField()),
                ('pastor', models.CharField(max_length=255)),
                ('church', models.CharField(max_length=255)),
                ('membership_status', models.BooleanField(default=False)),
                ('is_servant_of_god', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masteruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ServantOfGod', to='master.master', verbose_name='Master Data')),
            ],
            options={
                'verbose_name': 'Data Hamba Tuhan',
                'verbose_name_plural': 'Data Hamba Tuhan',
            },
        ),
        migrations.CreateModel(
            name='ServantOfGodProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Hamba Tuhan',
                'verbose_name_plural': 'Data Hamba Tuhan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.servantofgod',),
        ),
    ]
