# Generated by Django 5.0.4 on 2024-05-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
