# Generated by Django 5.0.4 on 2024-06-03 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_master_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Data Keluarga', 'verbose_name_plural': 'Data Keluarga'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Data Master', 'verbose_name_plural': 'Data Master'},
        ),
        migrations.AlterField(
            model_name='baptism',
            name='baptism_date',
            field=models.DateField(verbose_name='Tanggal Baptis'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Baptism', to='master.congregation', verbose_name='Data Jemaat'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Anak'), (2, 'Dewasa')]),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='alias_name',
            field=models.CharField(max_length=255, verbose_name='Nama Alias'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='chinese_name',
            field=models.CharField(max_length=255, verbose_name='Nama Chinese'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='is_congregation',
            field=models.BooleanField(default=False, verbose_name='Dia Jemaat?'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Congregation', to='master.master', verbose_name='DataMaster'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.IntegerField(verbose_name='Nomor Ibadah'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=255, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_employment',
            field=models.IntegerField(verbose_name='BPJS Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_health',
            field=models.IntegerField(verbose_name='BPJS Kesehatan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(max_length=255, verbose_name='Posisi Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Dia Karyawan?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='master.master', verbose_name='Data Master'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.IntegerField(verbose_name='Nomor ID Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.PositiveIntegerField(choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katholik'), (4, 'Hindu'), (5, 'Budha'), (6, 'Konghucu')], verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(verbose_name='Tanggal Mulai Kerja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='master.master', verbose_name='Data Keluarga'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Ayah'), (2, 'Ibu'), (3, 'Anak'), (4, 'Kakak'), (5, 'Adik')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Lokasi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='blood_type',
            field=models.PositiveIntegerField(choices=[(1, 'A+'), (2, 'B+'), (3, 'AB+'), (4, 'O+'), (5, 'A-'), (6, 'B-'), (7, 'AB-'), (8, 'O-')], verbose_name='Golongan Darah'),
        ),
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')], verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='master',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Masters', to='master.location', verbose_name='Lokasi Gereja'),
        ),
        migrations.AlterField(
            model_name='master',
            name='marital_status',
            field=models.PositiveIntegerField(choices=[(1, 'Belum Menikah'), (2, 'Menikah'), (3, 'Janda/Duda')], verbose_name='Status Perkawinan'),
        ),
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.IntegerField(verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/img', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='church',
            field=models.CharField(max_length=255, verbose_name='Nama Ibadah'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='is_servant_of_god',
            field=models.BooleanField(default=False, verbose_name='Dia Hamba Tuhan?'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='member_number',
            field=models.IntegerField(verbose_name='Nomor Hamba Tuhan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='membership_status',
            field=models.BooleanField(default=False, verbose_name='Status Membership'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='ordination',
            field=models.DateField(verbose_name='Tanggal Bapstis'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='pastor',
            field=models.CharField(max_length=255, verbose_name='Nama Pendeta'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
