# Generated by Django 5.0.4 on 2024-06-05 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_family_options_alter_master_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.IntegerField(verbose_name='Nomor Jemaat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9)], verbose_name='NIK/PASPOR'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
