# Generated by Django 5.0.4 on 2024-06-07 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_congregation_member_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(9)], verbose_name='NIK/PASPOR'),
        ),
    ]
