# Generated by Django 5.0.4 on 2024-06-07 02:32

import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_master_personal_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.IntegerField(validators=[master.models.validate_number_length], verbose_name='NIK/PASPOR'),
        ),
    ]
