# Generated by Django 5.0.4 on 2024-06-20 01:51

import django.db.models.deletion
import master.validates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_master_personal_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.IntegerField(unique=True, verbose_name='Nomor Jemaat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_employment',
            field=models.IntegerField(unique=True, verbose_name='BPJS Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_health',
            field=models.IntegerField(unique=True, verbose_name='BPJS Kesehatan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.IntegerField(unique=True, verbose_name='Nomor ID Karyawan'),
        ),
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.IntegerField(unique=True, validators=[master.validates.validate_number_length], verbose_name='NIK/PASPOR'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='member_number',
            field=models.IntegerField(unique=True, verbose_name='Nomor Hamba Tuhan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='ordination',
            field=models.DateField(verbose_name='Tanggal Pengangkatan'),
        ),
    ]
