# Generated by Django 5.0.4 on 2024-06-28 08:59

import django.db.models.deletion
import master.validates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_congregation_member_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pendeta', to='master.master', verbose_name='Data Jemaat'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Anak'), (2, 'Dewasa'), (3, 'Atestasi Masuk'), (4, 'Sidi')]),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Chinese'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.IntegerField(unique=True, verbose_name='Nomor Anggota Jemaat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(help_text='Wajib diisi', max_length=255, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='blood_type',
            field=models.PositiveIntegerField(choices=[(1, 'A+'), (2, 'B+'), (3, 'AB+'), (4, 'O+'), (5, 'A-'), (6, 'B-'), (7, 'AB-'), (8, 'O-')], help_text='Wajib diisi', verbose_name='Golongan Darah'),
        ),
        migrations.AlterField(
            model_name='master',
            name='full_name',
            field=models.CharField(help_text='Wajib diisi', max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')], help_text='Wajib diisi', verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='master',
            name='marital_status',
            field=models.PositiveIntegerField(choices=[(1, 'Belum Menikah'), (2, 'Menikah'), (3, 'Janda/Duda')], help_text='Wajib diisi', verbose_name='Status Perkawinan'),
        ),
        migrations.AlterField(
            model_name='master',
            name='personal_identity',
            field=models.CharField(help_text='Wajib diisi', max_length=16, unique=True, validators=[master.validates.validate_number_length], verbose_name='NIK/PASPOR'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[master.validates.isValidPhoneNumber], verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Wajib diisi', null=True, upload_to='profile_photo/img', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
