# Generated by Django 5.0.4 on 2024-06-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_baptism_congregation_alter_baptism_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pendeta', to='master.master', verbose_name='Pendeta'),
        ),
    ]
