# Generated by Django 5.0.4 on 2024-07-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_baptism_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='master.location', verbose_name='Lokasi Baptis'),
        ),
    ]
