# Generated by Django 5.0.4 on 2024-07-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_baptism_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Anggota Jemaat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor ID Karyawan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='church',
            field=models.CharField(max_length=255, verbose_name='Tempat Ibadah'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='member_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Hamba Tuhan'),
        ),
    ]
