# Generated by Django 5.0.4 on 2024-07-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_congregation_member_number_alter_employee_nik_and_more'),
        ('structural', '0005_alter_nonstructural_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='nonstructural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NonStructural', to='structural.nonstructural', verbose_name='Non Structural'),
        ),
    ]
