# Generated by Django 5.0.4 on 2024-07-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_master_nonstructural'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='latter_of_transfer',
            field=models.DateField(blank=True, null=True, verbose_name='Latter of Transfer'),
        ),
        migrations.AddField(
            model_name='master',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='master',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kematian'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Congregation', to='master.master', verbose_name='Nama Lengkap'),
        ),
    ]
