# Generated by Django 5.0.4 on 2024-07-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_congregation_latter_of_transfer_master_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Alias'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='latter_of_transfer',
            field=models.DateField(blank=True, help_text='Isi jika keluar dari gereja', null=True, verbose_name='Atestasi Keluar'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.CharField(help_text='<ul> <li>Wajid diisi</li> <li> Awalan (S), untuk simpatisan. </li><li> Selain itu adalah anggota jemaat. </li> </ul>', max_length=16, unique=True, verbose_name='Nomor Anggota Jemaat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Isi jika sudah meninggal', null=True, verbose_name='Tanggal Kematian'),
        ),
        migrations.AlterField(
            model_name='master',
            name='location',
            field=models.ForeignKey(help_text='Wajib diisi', on_delete=django.db.models.deletion.CASCADE, related_name='Masters', to='master.location', verbose_name='Lokasi Gereja'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='member_number',
            field=models.CharField(help_text='Tidak perlu di isi jika di jemaat sudah ada', max_length=16, unique=True, verbose_name='Nomor Hamba Tuhan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='ordination',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pengangkatan'),
        ),
    ]
