# Generated by Django 5.0.4 on 2024-07-16 02:32

import master.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_congregation_alias_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaptismProxy',
        ),
        migrations.DeleteModel(
            name='CongregationProxy',
        ),
        migrations.DeleteModel(
            name='EmployeeProxy',
        ),
        migrations.DeleteModel(
            name='FamilyProxy',
        ),
        migrations.DeleteModel(
            name='GalleryProxy',
        ),
        migrations.DeleteModel(
            name='ServantOfGodProxy',
        ),
        migrations.AddField(
            model_name='employee',
            name='out_of_work',
            field=models.DateField(blank=True, help_text='Isi jika sudah tidak menjadi karyawan', null=True, verbose_name='Tanggal Keluar Karyawan'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='baptism_date',
            field=models.DateField(help_text='Wajib diisi', verbose_name='Tanggal Baptis'),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Anak'), (2, 'Dewasa'), (3, 'Atestasi Masuk'), (4, 'Sidi')], help_text='Wajib diisi'),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.CharField(help_text='<ul> <li>Wajib diisi</li> <li> Awalan (S), untuk simpatisan. </li><li> Selain itu adalah anggota jemaat. </li> </ul>', max_length=16, unique=True, validators=[master.validates.isMemberNumberValid], verbose_name='Nomor Anggota Jemaat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(help_text='Wajib diisi', max_length=255, unique=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_employment',
            field=models.IntegerField(help_text='Wajib diisi', unique=True, verbose_name='BPJS Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_health',
            field=models.IntegerField(help_text='Wajib diisi', unique=True, verbose_name='BPJS Kesehatan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(help_text='Wajib diisi', max_length=255, verbose_name='Posisi Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Checklist jika ingin mengisi field karyawan', verbose_name='Dia Karyawan?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.CharField(help_text='Wajib diisi', max_length=16, unique=True, verbose_name='Nomor ID Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.PositiveIntegerField(choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katholik'), (4, 'Hindu'), (5, 'Budha'), (6, 'Konghucu')], help_text='Wajib diisi', verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(help_text='Wajib diisi', verbose_name='Tanggal Mulai Kerja'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Ayah'), (2, 'Ibu'), (3, 'Anak'), (4, 'Kakak'), (5, 'Adik')], help_text='Wajib diisi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Wajib diisi', max_length=255, verbose_name='Nama Lokasi'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='church',
            field=models.CharField(help_text='wajib diisi', max_length=255, verbose_name='Tempat Ibadah'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='is_servant_of_god',
            field=models.BooleanField(default=False, help_text='Checklist jika ingin mengisi field hamba tuhan', verbose_name='Dia Hamba Tuhan?'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='pastor',
            field=models.CharField(blank=True, help_text='Nama Pendeta yang mengangkat hamba tuhan ini', max_length=255, null=True, verbose_name='Nama Pendeta'),
        ),
    ]
