# Generated by Django 5.0.4 on 2024-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_delete_baptismproxy_delete_congregationproxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregation',
            name='latter_of_transfer',
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Anak'), (2, 'Dewasa'), (3, 'Atestasi Masuk'), (4, 'Atestasi Keluar'), (5, 'Sidi')], help_text='Wajib diisi'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Ayah'), (2, 'Ibu'), (3, 'Suami'), (4, 'Istri'), (5, 'Anak'), (6, 'Kakak'), (7, 'Adik'), (8, 'Kerabat')], help_text='Wajib diisi'),
        ),
    ]
