# Generated by Django 5.0.4 on 2024-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_remove_congregation_latter_of_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Mandarin'),
        ),
    ]
