# Generated by Django 5.0.4 on 2024-07-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_alter_congregation_chinese_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baptism',
            options={'verbose_name': 'Data Baptis / Atestasi', 'verbose_name_plural': 'Data Baptis / Atestasi'},
        ),
    ]
