# Generated by Django 5.0.4 on 2024-07-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_alter_baptism_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantofgod',
            name='church',
            field=models.CharField(blank=True, help_text='Isi jika dari tempat lain.', max_length=255, null=True, verbose_name='Tempat Pengangkatan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='membership_status',
            field=models.BooleanField(default=False, help_text='Checklist jika ', verbose_name='Status Keanggotaan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='pastor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pastor', to='master.master', verbose_name='Pendeta yang mengangkat'),
        ),
    ]
