# Generated by Django 5.0.4 on 2024-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_alter_servantofgod_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')], help_text='Wajib diisi', null=True, verbose_name='Jenis Kelamin'),
        ),
    ]
