# Generated by Django 5.0.4 on 2024-07-24 10:38

import django.db.models.deletion
import master.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_master_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='member_number',
            field=models.CharField(help_text='<ul> <li>Wajib diisi</li><li> Awalan (S), untuk simpatisan, contoh = S001 </li><li> Untuk Anggota hanya terdiri dari angka, contoh = 001</li><li> Jika mengisi no anggota Hamba Tuhan maka pada nomor anggota Jemaat akan berubah sesuai dengan yang di isi.</li> </ul>', max_length=16, unique=True, validators=[master.validates.isMemberNumberValid], verbose_name='Nomor Anggota Jemaat'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ServantOfGod', to='master.master', verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='member_number',
            field=models.CharField(help_text='<li> Awalan (S), untuk simpatisan, contoh = S001 </li><li> Untuk Anggota hanya terdiri dari angka, contoh = 001</li><li> Jika mengisi no anggota Hamba Tuhan maka pada nomor anggota Jemaat akan berubah sesuai dengan yang di isi.</li> </ul>', max_length=16, unique=True, validators=[master.validates.isMemberNumberValid], verbose_name='Nomor Hamba Tuhan'),
        ),
        migrations.AlterField(
            model_name='servantofgod',
            name='membership_status',
            field=models.BooleanField(default=True, help_text='Checklist jika masih aktif', verbose_name='Status Keanggotaan'),
        ),
    ]
