# Generated by Django 5.0.4 on 2024-07-25 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_alter_congregation_member_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='masteruser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='master.master', verbose_name='Nama Lengkap'),
        ),
    ]
