# Generated by Django 5.0.4 on 2024-06-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_create_general_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Konfigurasi Umum', 'verbose_name_plural': 'Konfigurasi Umum'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_edit',
            field=models.BooleanField(default=False, verbose_name='Bisa di edit'),
        ),
    ]
