# Generated by Django 5.0.4 on 2024-05-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warta',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
