# Generated by Django 5.0.4 on 2024-06-20 01:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warta', '0002_warta_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contents',
            field=tinymce.models.HTMLField(help_text='html is supported', verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Announcement/file', verbose_name='File Announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status Announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Url Announcement'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='warta/file', verbose_name='File Warta'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Highlight Warta'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Warta'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status Warta'),
        ),
        migrations.AlterField(
            model_name='warta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tanggal Diubah'),
        ),
    ]
