# Generated by Django 5.0.4 on 2024-07-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warta', '0003_alter_announcement_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warta',
            name='highlight',
        ),
    ]
