# Generated by Django 5.0.4 on 2024-07-24 02:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warta', '0004_remove_warta_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contents',
            field=tinymce.models.HTMLField(help_text='html is supported', verbose_name='Konten Pengunguman'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Announcement/file', verbose_name='File Pengumuman'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Pengumuman'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status Pengumuman'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Url Pengumuman'),
        ),
    ]
